spring:
  datasource:
    master:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/core
        username: root
        password:
    slave:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3307/core
        username: root
        password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect