spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/core
      username: root
      password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
