version: '3.8'

services:
  write:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'core'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  read-only:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'core'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
